# Generated by Django 3.1.4 on 2021-01-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'BILLING'), ('shipping', 'SHIPPING')], max_length=120),
        ),
    ]
